spring:
  application:
    name: url-shortener-backend

  profiles:
    active: dev

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

logging:
  level:
    root: INFO
    com.urlshortener: DEBUG

rate-limit:
  capacity: 3
  window-seconds: 60

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always